# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: Le blog de SRRoger
description: > # this means to ignore newlines until "email:"
  Le blog de SRRoger est un blog traitant de tout est de rien. 
  Musique, informatique, photographie, science, littérature et voyage.

email: roger_srey@hotmail.com
#blog logo
logo: "/assets/images/df_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/Best_2018-25.jpg"

name: 'Roger Srey'
author: 'Roger Srey'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.srroger.com" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
